package main

import (
	"io/ioutil"
	"flag"
	"fmt"
)

func main() {
	inFile := flag.String("in","","Input file")
	outFile := flag.String("out","","Output file")
	pkg := flag.String("package","main","Package name")
	name := flag.String("name","File","Identifier to use for the embedded data")
	asStr := flag.Bool("as-string",false,"Embed as string instead of []byte?")

	flag.Parse()

	inData, err := ioutil.ReadFile(*inFile)

	if err != nil {
		panic(err.Error())
	}

	comment := "// Code generated by go generate; DO NOT EDIT."

	var template string

	if !*asStr {
		template = "%s\npackage %s\n\nvar %s []byte = %#v\n"
	} else {
		template = "%s\npackage %s\n\nvar %s string = %q\n"
	}

	s := fmt.Sprintf(template, comment, *pkg, *name, inData)

	err = ioutil.WriteFile(*outFile, []byte(s), 0644)

	if err != nil {
		panic(err.Error())
	}
}
